f"${resistance:,.2f}")
col5.metric("ATR", f"${atr:,.2f}")

st.divider()

# Trade Setup
col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Entry", f"${entry:,.2f}")
col2.metric("🔴 Stop Loss", f"${sl:,.2f}")
col3.metric("🎯 TP1", f"${tp1:,.2f}")
col4.metric("🎯 TP2", f"${tp2:,.2f}")
col5.metric("🎯 TP3", f"${tp3:,.2f}")

st.info(f"Risk:Reward = 1:{rr:.1f} | BB Upper: ${bb_upper:,.2f} | BB Lower: ${bb_lower:,.2f}")

# Chart
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 8), gridspec_kw={'height_ratios': [3, 1]})
fig.patch.set_facecolor('#0e1117')
ax1.set_facecolor('#0e1117')
ax2.set_facecolor('#0e1117')

ax1.plot(df.index, close, color='white', linewidth=1.5, label='Price')
ax1.plot(df.index, ma20, color='orange', linewidth=1, linestyle='--', label='MA20')
ax1.plot(df.index, ma50, color='red', linewidth=1, linestyle='--', label='MA50')
ax1.plot(df.index, bb_mid, color='blue', linewidth=0.8, linestyle='--', label='BB Mid')
ax1.fill_between(df.index, bb_mid + 2*bb_std, bb_mid - 2*bb_std, alpha=0.1, color='blue', label='BB Bands')

ax1.axhline(y=resistance, color='#00ff88', linestyle=':', linewidth=1, label='Resistance')
ax1.axhline(y=support, color='#ff4444', linestyle=':', linewidth=1, label='Support')
ax1.axhline(y=entry, color='white', linestyle='-', linewidth=1.5, label='Entry')
ax1.axhline(y=sl, color='red', linestyle='--', linewidth=1.5, label='SL')
ax1.axhline(y=tp1, color='#00ff88', linestyle='--', linewidth=1, label='TP1')
ax1.axhline(y=tp2, color='#00cc66', linestyle='--', linewidth=1, label='TP2')
ax1.axhline(y=tp3, color='#009944', linestyle='--', linewidth=1, label='TP3')

ax1.set_title(f'{name} Chart', color='white', fontsize=14)
ax1.tick_params(colors='white')
ax1.spines['bottom'].set_color('#333')
ax1.spines['left'].set_color('#333')
ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)
ax1.legend(facecolor='#1a1a2e', labelcolor='white', fontsize=7, loc='upper left')
ax1.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))

delta2 = close.diff()
gain2 = delta2.where(delta2 > 0, 0).rolling(14).mean()
loss2 = -delta2.where(delta2 < 0, 0).rolling(14).mean()
rsi_line = 100 - (100 / (1 + gain2/loss2))
ax2.plot(df.index, rsi_line, color='purple', linewidth=1.5)
ax2.axhline(y=70, color='red', linestyle='--', linewidth=0.8)
ax2.axhline(y=30, color='green', linestyle='--', linewidth=0.8)
ax2.fill_between(df.index, rsi_line, 70, where=(rsi_line >= 70), alpha=0.3, color='red')
ax2.fill_between(df.index, rsi_line, 30, where=(rsi_line <= 30), alpha=0.3, color='green')
ax2.set_title('RSI', color='white', fontsize=10)
ax2.tick_params(colors='white')
ax2.spines['bottom'].set_color('#333')
ax2.spines['left'].set_color('#333')
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.set_ylim(0, 100)
ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))

plt.xticks(rotation=45, color='white')
plt.tight_layout()
st.pyplot(fig)
plt.close()

st.caption(f"Updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
